### ISSUE TITLE
GitGutter artifacts

### ISSUE THREAD

**Issue by rshkv** [junegunn/goyo.vim#128]
Hi @junegunn,

I have an issue with GitGutter. This is what I get when entering Goyo:

<img src="https://www.dropbox.com/s/xhe9inl5fyb00w3/Screenshot%202016-10-05%2018.43.59.png?dl=1" width="350px">

I understand that I can hook into Goyo's events but even if I call `:GitGutterDisable` from inside Goyo the light vertical bar doesn't go away (the line marks do).

<img src="https://www.dropbox.com/s/iirzcf7i0cu212x/Screenshot%202016-10-05%2018.50.31.png?dl=1" width="350px">

My version is `8`. With nvim `0.1.4` I get this: 

<img src="https://www.dropbox.com/s/lnlmgp2ybuobz64/Screenshot%202016-10-05%2018.55.19.png?dl=1" width="350px">

I'm rather new to Vim and it's likely that I have something in my [vimrc](https://gist.github.com/rshkv/9f351c105b6497cf71a84a83d616d924) messing with Goyo. The _goyo_ experience is dear to me and I'd be happy if you could point me in the right direction.

<script src="https://gist.github.com/rshkv/9f351c105b6497cf71a84a83d616d924.js"></script>

**Comment by junegunn** [comment]
As noted in the README page, Goyo disable gitgutter by default.

https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L199-L203

It used to work well, but I can confirm that it doesn't work as expected with the latest version of gitgutter. Since the problem is reproducible without Goyo with the following snippet, you might want to report the problem to the author of gitgutter.

```vim
" GitGutterDisable immediately following tab split does not clear signs
tab split | GitGutterDisable
```

**Comment by rshkv** [comment]
Thank you @junegunn,

I understand, and opened an issue with GitGutter. 
You can close this issue here or wait until the guys at GitGutter have responded.

**Comment by rshkv** [comment]
The issue was resolved in the referenced issue.

**Comment by junegunn** [comment]
Thanks.
