### ISSUE TITLE
Add documentation for vim

### ISSUE THREAD

**Issue by ultimatecoder** [junegunn/goyo.vim#144]
* **Description:** Recently I was trying to look this plugin. I found it does have guidelines at **README.md** file but it is missing the documentation for vim editor. I believe it is required to provide one copy of documentation so that the user don't have to come here for it. Providing vim help can be a more handy option than providing help here.

* **What I can do?**
I have never written any help for any vim plugin before. But I want to get some experience on it. If someone is able to provide proper guidance I am happy to do this job.

**Comment by junegunn** [comment]
I appreciate your proposal, but I have a private script for converting markdown document to vim help file, so  that's not necessary.

While I agree that providing vim help is beneficial for the users, I personally don't like having to maintain the document in two different formats and keep them in sync. I'll think about it.

Having said that, since nowadays we install plugins by cloning the whole repository using a plugin mananger, README.md file should be available on the user's disk drive. If you use vim-plug and fzf.vim, you can browse the plugins files and find README.md file under a certain plugin directory.

```sh
:execute 'Files' g:plug_home
```

**Comment by chreekat** [comment]
> While I agree that providing vim help is beneficial for the users, I personally don't like having to maintain the document in two different formats and keep them in sync. I'll think about it.

Please do. :) One of the most valuable implicit contracts that plugin writers uphold in Vim is the inclusion of help files. I understand that you don't want to maintain two sets of documents (vim and README), but I believe if you have to choose, choose help.

**Comment by chreekat** [comment]
In the meanwhile, https://github.com/ultimatecoder/goyo-doc
