### ISSUE TITLE
Colors break when exiting - Peaksea

### ISSUE THREAD

**Issue by Donkeyfish87** [junegunn/goyo.vim#146]
I use the Peaksea color scheme. When I enter distraction free mode it works like it should, but the colors are reversed (light-grey background) when I exit. The only way (I have discovered)  to revert is to restart vim.

I tried with a different colorscheme, solarized, which didn't have this issue.

**Comment by ultimatecoder** [comment]
@Donkeyfish87 I tried after installing peaksea colorscheme. I am able to reproduce this bug.

**Comment by ultimatecoder** [comment]
Reference to Peaksea colorscheme: http://www.vim.org/scripts/script.php?script_id=760

**Comment by ffesseler** [comment]
Same issue with Tomorrow-Night colorscheme

**Comment by junegunn** [comment]
It's a bug of the color scheme. You can reproduce the problem without Goyo just by reloading the color scheme: repeat `:colo peaksea`. And you're running into this since Goyo reloads the current color scheme on exit to restore the colors. A workaround for this particular color scheme would be to set up GoyoLeave autocmd as follows.

```vim
autocmd! User GoyoLeave nested set bg=dark | colo peaksea
```
