### ISSUE TITLE
SignColumn color not restored when leaving Goyo

### ISSUE THREAD

**Issue by alexlafroscia** [junegunn/goyo.vim#51]
I noticed that the `SignColumn`'s background is set wrong when leaving Goyo.

Before entering Goyo:

![screen shot 2015-01-21 at 6 57 52 pm](https://cloud.githubusercontent.com/assets/1645881/5847807/7c721566-a19f-11e4-889d-b93b3a429579.png)

After leaving Goyo

![screen shot 2015-01-21 at 6 58 14 pm](https://cloud.githubusercontent.com/assets/1645881/5847810/8090c73c-a19f-11e4-92b0-70a3d6271551.png)

I was able to help a little bit by re-setting the SignColumn color upon leaving Goyo, but it only affected rows where the gutter wasn't being used; any rows that actually were making use of the gutter (for Git status, for example) remained the wrong color.

**Comment by junegunn** [comment]
I haven't run into this problem. Could you provide me with a minimal vimrc that can reproduce the problem? I mean without any other irrelevant plugins or settings.

**Comment by wookayin** [comment]
I ran into a similar issue. The highlight values of `SignColumn`, `GitGutterAdd`, etc. are all lost after leaving Goyo. Shouldn't `Goyo` restore existing highlights rather than simply discarding them away?

Steps to reproduce:
```
❯❯❯ nvim -u <(cat <<EOF
set rtp+=~/.vim/plugged/goyo.vim/
set rtp+=~/.vim/plugged/vim-gitgutter/
source ~/.vim/plugged/goyo.vim/plugin/goyo.vim
source ~/.vim/plugged/vim-gitgutter/plugin/gitgutter.vim
set termguicolors
hi SignColumn guibg=red
EOF
)
```

Open any file inside a git repository:
- `:Goyo`   " enter
- `:Goyo`   " leave

and then SignColumn is lost.
