### ISSUE TITLE
Window scrolls as text reaches margin

### ISSUE THREAD

**Issue by tlvince** [junegunn/goyo.vim#6]
Is there a way to prevent the following horizontal scrolling? (Ignore the completion flickers; that's YCM going wild).

![goyo](https://f.cloud.github.com/assets/323761/1673139/979d3c7a-5ce1-11e3-84c9-5a0e9133eddd.gif)

(NB, I also notice a few seconds delay after Goyo is called. Is this expected?).

**Comment by mlongval** [comment]
Hello junegunn,

I like Goyo very much. Thanks for writing it.

I am not very good at VIM and would like to change the top and bottom margins.

I have found that I should be doing something like this:

    :set goyo_margin_top=0 

But when I do it I get an error "Unknown option: goyo_margin_top"

Thanks again,

Mike

**Comment by junegunn** [comment]
@mlongval Hi, you should use `let` instead of `set`. Add the following lines to your .vimrc

```vim
let g:goyo_margin_top = 0
let g:goyo_margin_bottom = 0
```

However, please note that due to the limitation of the current implementation, you can't reduce the top and bottom margin down to zero. They will still take 2-3 lines even if you set `g:goyo_margin_top` and `g:goyo_margin_bottom` to zero.

**Comment by mlongval** [comment]
Thanks junegunn.  

Cheers! ;)

**Comment by kartik-ynwa** [comment]
I had this issue too. Using vim-pencil causes lines to not wrap immediately sometimes when it reaches the `textwidth`. I fixed this by `let g:goyo_width = 90`. Just thought I would leave this here.

Thanks for this great extension by the way.
