### ISSUE TITLE
`:q` [in goyo] moves cursor to top of buffer in original window 

### ISSUE THREAD

**Issue by orbisvicis** [junegunn/goyo.vim#64]
Let me know if extra info required.

**Comment by junegunn** [comment]
Running goyo is effectively equivalent to doing the following.

```vim
" Open a buffer

" Open it in a new tab
:tab split

" Move the cursor

" Close the tab
:q
```

The cursor in the original window is not synchronized. Goyo tries to restore the position of the buffer when it's possible, but it doesn't work when you close Goyo window with `:q`, it's a known issue. Closing Goyo window by leaving the tab (e.g. `gt`) will work.

See: https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L309-L312

**Comment by indiofish** [comment]
function! s:goyo_leave()
"two single '  not "
  ''
endfunction

adding this in .vimrc and calling it as suggested in the readme seems to provide a workaround to the problem, at least in my case. 
Although this issue is closed, and though this is not a perfect solution (if you 'jumped' by gg, running Goyo and closing it with :q will take you to the position before you pressed gg) I will post it just in case.
