### ISSUE TITLE
Truly marvelous margin ideas, which this title box is too narrow to contain

### ISSUE THREAD

**Issue by gfixler** [junegunn/goyo.vim#68]
This is a feature request [or three] that I've been wanting for a while now, which would really make goyo.vim useful in more situations. Right now, with the baked-in margin values, Goyo isn't usable if I zoom in on the terminal with `Ctrl Shift +` during a work demo, or change layouts in i3 (tiling wm), or split up the Vim window, or tmux pane, or work in a window. I think my dream would be this:

* absolute horizontal limit, as now, but don't shrink below that if the window is too narrow
* absolute vertical limit, and again, don't shrink below this if the window isn't tall enough.
* `<count>` for percentage of window height (e.g. `30<goyo map>` = 30% tall content, 70% margins)
* different command for entering with an absolute height (e.g. `30<other map>` = 30-line tall view)
* margin-moving commands, which take counts, e.g. GoyoLeftWider/Narrower, GoyoTopTaller
* mirrored margin-moving commands, which take counts, e.g. GoyoWider, GoyoTaller/Shorter

**Comment by junegunn** [comment]
Thanks for the suggestion but I have to mention that I'm currently not very interested in adding more features. (I particularly like that Goyo being simple with only a single command.)

> absolute horizontal limit, as now, but don't shrink below that if the window is too narrow

`:Goyo` command takes an optional width argument, so you can use it to resize Goyo window on `VimResized` event.

```vim
function! s:goyo_enter()
  augroup adjust_goyo
    autocmd!
    autocmd VimResized * execute 'Goyo' min([&columns / 2, 80])
  augroup END
endfunction

function! s:goyo_leave()
  augroup adjust_goyo
    autocmd!
  augroup END
endfunction

autocmd! User GoyoEnter
autocmd! User GoyoLeave
autocmd  User GoyoEnter nested call <SID>goyo_enter()
autocmd  User GoyoLeave nested call <SID>goyo_leave()
```

> absolute vertical limit, and again, don't shrink below this if the window isn't tall enough

However, there's currently no equivalent way to set absolute height. Maybe it would be a good idea to extend the optional argument to take the height as well, e.g. `:Goyo 80`, `:Goyo 80x80`, `:Goyo x80`. But then it will not be compatible with `g:goyo_margin_top` and `g:goyo_margin_bottom`. Hmm.

Regarding the key mappings, have you tried [the default mappings](https://github.com/junegunn/goyo.vim#usage) that Goyo overrides? They are not as specific as your requirements, but I find them good enough for most cases, and the good thing is that they follow Vim convention and do not "invent" anything that a user has to learn.

> margin-moving commands, which take counts, e.g. GoyoLeftWider/Narrower, GoyoTopTaller

I'm not sure if we really need this. Can you explain why you need it? And if we decided to add the feature, I'd like to extend the optional argument to `:Goyo` instead of adding a bunch of new commands. e.g. `:Goyo 80-5x80+5`

**Comment by junegunn** [comment]
See the updated README page. Now you can pass width, height and offsets either in absolute numbers or in relative percentages to `:Goyo` command.

1. Start Goyo in 50% by 50% size.
```vim
Goyo 50%x50%
```
2. You can adjust its size with the usual `[count]CTRL-W[><+-]`
3. Resize terminal
4. Because of the possibility of 2, we do not know if the recalculation of width and height is desirable
4. Manually pressing `CTRL-W=` will readjust the size to 50% x 50% of the new terminal size

So now with this new dimension expression, I believe that you should be able to implement a custom resize handler by extending the example I gave you above.

**Comment by gfixler** [comment]
>currently not very interested in adding more features.

Understandable. I appreciate small, focused things, and this plugin is all about focus :)

>:Goyo command takes an optional width argument

I think I was very out of date on the plugin. If not, I somehow missed that I could do this. This is great. This gets me the 4th bullet point, "command for entering with an absolute height."

>You can adjust its size with the usual [count]CTRL-W[><+-]

Where did these come from!? Again, quite out of date, I guess, but these are exactly what I'd want. I use the `<C-w>` keys all the time, and I love that these only exist in the goyo window. Great stuff, and this gets me my 6th bullet point: "mirrored margin-moving commands."

>Now you can pass width, height and offsets either in absolute numbers or in relative percentages

Wow, this is most of the rest of the bullet points!

>Manually pressing CTRL-W=

And this basically finishes off the list. You've given me either exactly what I wanted, or the tools to roll what I want for the few last bits. Thanks very much! Goyo just became ideal for me.

**Comment by junegunn** [comment]
Cool, thanks.
