### ISSUE TITLE
Can't switch to NERDTree

### ISSUE THREAD

**Issue by nunoh** [junegunn/goyo.vim#69]
When writing markdown blog posts I find it useful to keep NERDTree open in the top left corner to switch between articles and drafts. However, can't seem to be able to do that? Is this plain outright not supported in your plugin or maybe you could be so kind as to give me some pointer on how do to it? 

Btw, I'm able to `C-W l` (switch away from NERDTree to the current buffer) but not `C-W h` (switch from the current buffer back to NERDTree).

Thanks.

**Comment by junegunn** [comment]
In order to position the buffer on the center of the screen, Goyo surrounds it with 4 invisible "pad" buffers. And obviously they are "implementation details" and the user should not end up in those buffers in any case. So when the cursor enters any of the buffers, either by CTRL-W-something, or by a mouse click, Goyo sends back the cursor to the central window. So that's what you're experiencing. Maybe we could find a smarter way to handle this, but currently a workaround is to skip over the pad buffer by `2<CTRL-W>h`, or to use mouse to click the nerdtree pane.

**Comment by nunoh** [comment]
Ok. That makes a lot of sense. Thanks for the pointer! 

Btw, fan of your plugins. Use them on a daily basis, so thanks. :bow:

**Comment by junegunn** [comment]
Thanks.
