### ISSUE TITLE
Goyo doesn't honor configurations when changing terminal window size back and forth

### ISSUE THREAD

**Issue by oblitum** [junegunn/goyo.vim#79]
My Goyo setup is this:

```vim
" Goyo Setup {{{
let g:goyo_margin_top = 2
let g:goyo_margin_bottom = 2

function! s:goyo_enter()
    silent !tmux set status off
endfunction

function! s:goyo_leave()
    silent !tmux set status on
endfunction

au! User GoyoEnter
au! User GoyoLeave
au  User GoyoEnter nested call <SID>goyo_enter()
au  User GoyoLeave nested call <SID>goyo_leave()
" }}}
```

I generally use my terminal fullscreen. If I switch to windowed mode and back to fullscreen, Goyo top and bottom margins get screwed, they cover almost all area if I'm switching back from a small window size to fullscreen. It's as if in fullscreen the area for text content displayed remains the same as the area shown when in a small window.

**Comment by oblitum** [comment]
By the way, I'm using tmux on gnome terminal.

**Comment by oblitum** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2015 13:02:23)
Included patches: 1-812

**Comment by junegunn** [comment]
Actually, that is the expected behavior. Goyo resizes the surrounding windows on VimResized event, but not the central window in order not to override the user's decision. Say, a user starts Goyo with the default width of 80 and resizes the window with `5CTRL-W >`, and the width of the central window is 90. Then on VimResized, Goyo adjusts the sizes of the surrounding windows, but keeps the width of the central window to be 90. Goyo does not keep track of whether the current dimension is due to the user's previous action or due to the truncation from terminal resize. Think about all the possible cases, it gets pretty messy.

Anyway, you can hit `CTRL-W =` to resize the window to its initial size.

**Comment by oblitum** [comment]
Thanks Junegunn, I didn't know ctrl-w would do it, it's enough for me.

**Comment by muiraie** [comment]
```
" On window resize, if goyo is active, do <c-w>= to resize the window
autocmd VimResized * if exists('#goyo') | exe "normal \<c-w>=" | endif
```

from https://github.com/junegunn/goyo.vim/issues/159#issuecomment-342417487
