### ISSUE TITLE
Sessions do not restore Goyo state

### ISSUE THREAD

**Issue by Lavvrence** [junegunn/goyo.vim#82]
After `:mks!' and `:xa' from within Goyo and `vim -S' at cmd line, the Goyo session is restored in a messed up state. Is there perhaps a way to fix this?

**Comment by junegunn** [comment]
Hmm, I don't think it's possible. If you open the session file, you'll notice that it's just a Vimscript file and it does not contain any information about colors (e.g. `colorscheme`, `highlight`). Maybe there's a plugin that somehow extends the feature so that it also includes those settings. Maybe.
